name: CI
on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
        
      - name: Update npm
        if: matrix.platform == 'windows-latest'
        run: npm install --global npm@latest

      - name: Patch node-gyp to support Visual Studio 2019
        if: matrix.platform == 'windows-latest'
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: test:win
        if: matrix.platform == 'windows-latest'
        run: npm run test:win
      - name: test
        if: matrix.platform != 'windows-latest'
        run: npm run test:ci
      - name: lint
        run: npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
