name: CI
on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types:
      - created
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: test:win
        if: matrix.platform == 'windows-latest'
        run: npm run test:win
      - name: test
        if: matrix.platform != 'windows-latest'
        run: npm run test:ci
      - name: lint
        run: npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      cli_s3_bucket_key: ${{ steps.publish_cli.outputs.s3-bucket-key }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: Publish
        id: publish_cli
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
          
          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: 'decentraland-cli/branch/${{ github.head_ref || github.ref }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

  notify_deployment:
    needs: [publish]
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    name: Deployment Notification
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test this pull request
      - name: Generate S3 URL
        id: url-generator
        run: |
          body=$(echo ${{ secrets.SDK_TEAM_S3_BASE_URL }})/${{ needs.build.outputs.cli_s3_bucket_key }}
          echo ::set-output name=body::$body
      - name: Test Install S3 URL
        run: mkdir -p test_s3 && cd test_s3 && npm init --yes && npm install "${{ steps.url-generator.outputs.body }}"
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            - The `cli` package can be tested by globally install
               ```bash
               npm i -g "${{ steps.url-generator.outputs.body }}"
               ```
          edit-mode: replace